<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use Carbon\Carbon;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {

        DB::table('admins')->insert([
            'name'       => 'Admin',
            'username'   => 'admin',
            'password'   => Hash::make('admin'),
            'photo'      => null,
            'email'      => Str::random(10) . '@gmail.com',
            'role'       => 'super admin',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'deleted_at' => null,
        ]);

        DB::table('banners')->insert([
            [
                'picture'    => env('APP_URL') . '1.png',
                'url'        => '#',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'picture'    => env('APP_URL') . '2.png',
                'url'        => '#',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'picture'    => env('APP_URL') . '3.png',
                'url'        => '#',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ]
        ]);

        DB::table('master_areas')->insert([
            [
                'name'       => 'Jakarta - Bandara Internasional Soekarno-Hatta',
                'area_type'  => 'departure',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'name'       => 'Jakarta Utara',
                'area_type'  => 'arrival',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'name'       => 'Jakarta Timur',
                'area_type'  => 'arrival',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'name'       => 'Jakarta Selatan',
                'area_type'  => 'arrival',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'name'       => 'Jakarta Barat',
                'area_type'  => 'arrival',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'name'       => 'Jakarta Pusat',
                'area_type'  => 'arrival',
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
        ]);

        DB::table('master_sub_areas')->insert([
            [
                'master_area_id' => 1,
                'name'           => 'Terminal 1A',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 1,
                'name'           => 'Terminal 1B',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 1,
                'name'           => 'Terminal 2D',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 1,
                'name'           => 'Terminal 2E',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 1,
                'name'           => 'Terminal 2F',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 1,
                'name'           => 'Terminal 3',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 2,
                'name'           => 'Cilincing',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 2,
                'name'           => 'Kelapa Gading',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 2,
                'name'           => 'Koja',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 2,
                'name'           => 'Pademangan',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 2,
                'name'           => 'Penjaringan',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 2,
                'name'           => 'Tanjung Priok',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Cakung',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Cipayung',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Ciracas',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Duren Sawit',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Jatinegara',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Kramat Jati',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Makasar',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Pasar Rebo',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 3,
                'name'           => 'Pulo Gadung',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Cilandak',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Jagakarsa',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Kebayoran baru',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Kebayoran Lama',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Mampang Prapatan',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Pancoran',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Pasar Minggu',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Pesanggrahan',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Setiabudi',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 4,
                'name'           => 'Tebet',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Cengkareng',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Grogol Petamburan',
                'is_active'      => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Taman Sari',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Tambora',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Kebon Jeruk',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Kalideres',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Palmerah',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 5,
                'name'           => 'Kembangan',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Cempaka Putih',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Gambir',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Johar Baru',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Kemayoran',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Menteng',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Sawah Besar',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Senen',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'master_area_id' => 6,
                'name'           => 'Tanah Abang',
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
        ]);

        for ($i = 7; $i <= 47; $i++) {
            DB::table('master_special_areas')->insert([
                [
                    'master_sub_area_id' => $i,
                    'first_person_price' => 10,
                    'extra_person_price' => 5,
                    'is_active'          => 'yes',
                    'notes'              => null,
                    'created_at'         => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at'         => Carbon::now()->format('Y-m-d H:i:s'),
                    'deleted_at'         => null,
                ],
            ]);
        }

        DB::table('vehicles')->insert([
            [
                'name'       => 'Car 1',
                'number'     => 'B 1234 CCD',
                'total_seat' => 15,
                'photo'      => null,
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'name'       => 'Car 2',
                'number'     => 'B 5678 CCD',
                'total_seat' => 19,
                'photo'      => null,
                'is_active'  => 'yes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
        ]);

        DB::table('luggage_prices')->insert(['price' => 1]);
        DB::table('privacies')->insert(['notes' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque, architecto!']);
        DB::table('term_and_conditions')->insert(['notes' => 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis similique sapiente autem dolorem amet fugit numquam repellendus voluptas fugiat tempore?']);

        DB::table('schedules')->insert([
            [
                'from_id'            => 1,
                'from_table'         => 'master_sub_areas',
                'to_id'              => 7,
                'to_table'           => 'master_sub_areas',
                'vehicle_id'         => 1,
                'datetime_departure' => Carbon::now()->format('Y-m-d H:i:s'),
                'datetime_arrival'   => Carbon::now()->addHours(4)->format('Y-m-d H:i:s'),
                'schedule_type'      => 'one way',
                'is_active'          => 'yes',
                'photo'              => null,
                'normal_price'       => 25,
                'driver_contact'     => '+62123456789',
                'notes'              => 'Lorem ipsum dolor sit amet.',
                'created_at'         => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'         => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'         => null,
            ],
            [
                'from_id'            => 1,
                'from_table'         => 'master_sub_areas',
                'to_id'              => 7,
                'to_table'           => 'master_sub_areas',
                'vehicle_id'         => 1,
                'datetime_departure' => Carbon::now()->format('Y-m-d H:i:s'),
                'datetime_arrival'   => Carbon::now()->addHours(4)->format('Y-m-d H:i:s'),
                'schedule_type'      => 'charter',
                'is_active'          => 'yes',
                'photo'              => null,
                'normal_price'       => 25,
                'driver_contact'     => '+62123456789',
                'notes'              => 'Lorem ipsum dolor sit amet.',
                'created_at'         => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'         => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'         => null,
            ],
        ]);

        DB::table('vouchers')->insert([
            [
                'name'           => 'Discount 10%',
                'code'           => 'promo10%',
                'date_start'     => '2022-09-01',
                'date_expired'   => '2022-10-31',
                'discount_type'  => 'percentage',
                'discount_value' => 10,
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
            [
                'name'           => 'Media Social Promo',
                'code'           => 'medsos',
                'date_start'     => '2022-09-01',
                'date_expired'   => '2022-10-31',
                'discount_type'  => 'value',
                'discount_value' => 5,
                'is_active'      => 'yes',
                'created_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at'     => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at'     => null,
            ],
        ]);
    }
}
